include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: [build/**]
  enable-experiment:
   - super-mixins
   - no-slow-checks
  strong-mode:
    #implicit-casts: false
    #implicit-dynamic: false

linter:
  rules:
    - camel_case_types